### ISSUE TITLE
please drop this library feeds, its not even maintained anymore

### ISSUE THREAD

**Issue by slidenerd** [qsniyg/webrssview#4]
https://www.npmjs.com/package/feeds
See, 5 years ago?

**Comment by qsniyg** [comment]
I don't understand though, I don't believe this project uses it...

`find node_modules | grep feeds` doesn't show anything.

Are you speaking about [feedparser](https://www.npmjs.com/package/feedparser)?

**Comment by slidenerd** [comment]
Apologies must be a nested dependency

**Comment by slidenerd** [comment]
As a side note I wanted to add many things

1. Your code doesnt have tests, probably a good idea to write one
2. monk is not exactly a great way to deal with mongodb, a better suggestion would be mongoose
3. You dont need to write so many promises, better idea to async await everything
4. This function of yours check_updated_item inside reload.js file uses a function called fuzzy_compare which in turn uses fuzzify_text you. this is not an accurate way to compare if the news title and item has changed, what if 2 news articles arrived, one was "hello world" and other was "HELLO world" the suggestion here would be to convert everything to lower case and then create an MD5 hash of it and compare the hashes together

**Comment by slidenerd** [comment]
```
(node:2906) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Listening on 8765
(node:2906) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
(node:2906) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
Done initialization (0,0 timers)
(node:2906) UnhandledPromiseRejectionWarning: [object Array]
(node:2906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
You also keep getting these errors, any ideas where they are coming from

**Comment by qsniyg** [comment]
Thank you for the code review!

1) Good point, I often forget to write tests
2) This was my first project using MongoDB, and monk was recommended for beginners which is why I picked it. If I have to rewrite any code interacting with the DB, I'll definitely consider using another library (monk has been a little limiting), but for now I think switching engines will likely introduce regressions (as any rewrite usually does) with little benefit. I looked into mongoose a while ago for another project, it looked pretty nice, but I didn't try it much, I'll have to give it another shot soon.
3) You're right, I should really do that haha, the code has become quite horizontal because of the promises
4) The reason for using fuzzy_compare is because I was using it with an Instagram->RSS converter I wrote ([rssit](https://github.com/qsniyg/rssit)), which would frequently update the image path, even though the article contents themselves didn't change. Please correct me if I misunderstood you, but are you suggesting that fuzzify_text should also turn it lowercase to ignore case checks? For me, if the text changes case, that would be grounds for an updated article, as it is a visible change. Good idea for the MD5 hash though, storing a hash of the old contents would speed up the check. In case fuzzify_text changes in the future, I'm guessing a good idea would be to first check the hash, and if they don't match, then recompute it again and check. Slightly slower for updated articles, but definitely much faster for most cases.

About the errors, I'm not sure, I don't see them on my side... I'm pretty sure this is on monk's side though, as the code doesn't directly interface with MongoClient (as stated in the error).
